# Generated by Django 2.1.4 on 2018-12-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181126_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('costo_pre', models.IntegerField(default=0)),
                ('costo_real', models.IntegerField(default=0)),
                ('tienda', models.CharField(max_length=255)),
                ('nota_aditional', models.TextField(default='')),
            ],
        ),
    ]
